import type { Metadata } from 'next';
import LegalPageShell from '@/components/LegalPageShell';
import { PRODUCT_NAME, LEGAL_ENTITY, LEGAL_CONTACT_EMAIL } from '@/lib/legal';

export const metadata: Metadata = {
  title: `Disclaimer · ${PRODUCT_NAME}`,
  description: 'Important disclaimer regarding the use of Compliance Guard Pro.',
};

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-2">{children}</h2>;
}

export default function DisclaimerPage() {
  return (
    <LegalPageShell title="Disclaimer">
      <p>
        {PRODUCT_NAME} (the &ldquo;Service&rdquo;), operated by {LEGAL_ENTITY}, is a software tool
        that helps facilities organize, track, and monitor documentation related to regulatory
        compliance. Please read this disclaimer carefully.
      </p>

      <H2>Not legal, regulatory, or professional advice</H2>
      <p>
        The Service does not provide legal advice and is not a substitute for the advice of a
        licensed attorney, compliance professional, or your applicable regulatory authority.
        Information, scores, checklists, and recommendations generated by the Service are provided
        for informational and organizational purposes only. You are solely responsible for your
        facility&rsquo;s compliance with all applicable federal, state, and local laws, rules, and
        licensing requirements.
      </p>

      <H2>No guarantee of compliance or audit outcomes</H2>
      <p>
        A readiness score, &ldquo;ready&rdquo; status, or completed checklist within the Service
        does <strong>not</strong> guarantee that your facility is in compliance, will pass an
        inspection or audit, or will avoid citations, penalties, or adverse action. Regulations
        change frequently and may be interpreted or enforced differently by the relevant agencies.
        You must independently verify all requirements with the official source.
      </p>

      <H2>Accuracy of regulatory content</H2>
      <p>
        We work to keep the regulatory criteria in the Service accurate and current, but we make no
        warranty that the content is complete, error-free, or up to date at any given time. The
        official statutes, rules, and licensing standards published by the applicable governing
        bodies always control.
      </p>

      <H2>Document and license verification</H2>
      <p>
        Certain features assist with reviewing or recording credentials and documents, including
        automated extraction and (where available) third-party verification services. These
        features are aids, not authoritative determinations. Records marked
        &ldquo;self-reported&rdquo; reflect information entered by you or your staff and have not
        been independently verified. You are responsible for confirming the authenticity and
        validity of any credential through its primary source.
      </p>

      <H2>Questions</H2>
      <p>
        If you have questions about this disclaimer, contact us at{' '}
        <a className="text-blue-600 hover:text-blue-700" href={`mailto:${LEGAL_CONTACT_EMAIL}`}>
          {LEGAL_CONTACT_EMAIL}
        </a>
        .
      </p>
    </LegalPageShell>
  );
}
